VERSION=${CIRCLE_BUILD_NUM-Unknown}
QUARTIC_DOCKER_REPOSITORY=${QUARTIC_DOCKER_REPOSITORY-quartic}

docker build -t $QUARTIC_DOCKER_REPOSITORY/orinoco:$VERSION .
docker build -t $QUARTIC_DOCKER_REPOSITORY/national-grid:$VERSION ./national-grid
